docs/index.html
The id(#transferring-items-or-coins-gifting-) is wrong and [link](https://projectopensea.github.io/opensea-js/index.html#transferring-items-or-coins-gifting) on the [document page](https://projectopensea.github.io/opensea-js/index.html)  is broken.
=> Fix docs link delete unnecery -

README.md
Fix typos at lines 343 and 465
=> Update README.md - fix typos

README.md
Add information about total buy order value to wallet balance ratio limit.
=> Add a sentence about offer limits

src/seaport.ts
__namedParamters -> __namedParameters
paramters -> parameters
=> fix typo in seaport.ts

src/api.ts
Spelling fix at line 236. Grammar fix at line 267.
=> Minor grammar and spelling fix

.vscode/settings.json, package.json, src/seaport.ts, yarn.lock
Can be done by checking the authenticated proxy
=> Add ability to freeze listings

package.json, src/seaport.ts, src/utils/utils.ts
send is not supported/standardized between all providers so revert back to using sendAsync
=> Use provider.sendAsync instead of send

package.json
Bump version to v4.0.2 with following fixes:
- https://github.com/ProjectOpenSea/opensea-js/pull/583
- https://github.com/ProjectOpenSea/opensea-js/pull/599
=> chore: Bump version v4.0.3

README.md
Removal of Affiliate compensation reference in SDK.
=> Updated README - Removal of old Affiliate info

README.md
Removes an invalid example link to an demo application.
=> Remove old example link

src/sdk.ts
I did the fix for the buy order, but not the sell order 😓
=> fix: sell order consideration items

README.md
Resolves these PRs:
https://github.com/ProjectOpenSea/opensea-js/pull/221
https://github.com/ProjectOpenSea/opensea-js/pull/496
https://github.com/ProjectOpenSea/opensea-js/pull/758
=> fix more readme typos

package.json
- Update homepage to V2 API.
- Update description to match API docs.
=> Update package.json fields

src/__integration_tests__/README.md, src/__integration_tests__/getCollection.ts, src/__integration_tests__/init.ts, src/__integration_tests__/postOrder.ts, src/__tests__/constants.ts, src/types.ts, src/utils/utils.ts
Added SafelistStatus Enum
Added safelistRequestStatus to OpenSeaCollection
Added safelistRequestStatus to collectionFromJSON
=> Added Collection verification status to api.getAsset (#729)

package-lock.json, package.json, src/utils/schemas/main/CryptoKitties/index.ts
Remove package which was only used by CryptoKitties.
=> Remove dependency on axios

package-lock.json, package.json, src/utils/utils.ts
These do not need to be asserted because we are using Typescript
=> Remove @0x/assert dependency

.github/workflows/stale.yml, package-lock.json, src/__integration_tests__/getAsset.ts, src/__integration_tests__/getCollection.ts, src/types.ts, src/utils/utils.ts
This is only a merge commit from master -> v6. All the code besides merge conflicts is already reviewed.
=> Sync v6 with master

package-lock.json, package.json
On windows, there's no true. Looking at other popular packages, I believe `|| exit 0` is a more reliable way to handle this .
=> Use exit 0 instead of || true to make sure postinstall works on Windows

.gitignore, src/types.ts, src/utils/utils.ts
zora now live in prod
already updated here: https://docs.opensea.io/reference/supported-chains
=> feat: add zora chain identifiers

package.json
=> Update package.json - minor version bump

.github/workflows/code-quality.yml, package-lock.json, package.json, src/api/types.ts, src/sdk.ts, src/utils/utils.ts, test/integration/README.md, test/integration/postOrder.spec.ts, test/integration/setup.ts, test/sdk/fees.spec.ts, test/sdk/misc.spec.ts, test/sdk/orders.spec.ts, test/utils/constants.ts
Adds multichain support to createBuyOrder/createSellOrder
=> add multichain support to createBuyOrder/createSellOrder

src/api/api.ts, src/sdk.ts, test/integration/postOrder.spec.ts
Fixes user encountered issues, https://github.com/ProjectOpenSea/opensea-js/issues/1092
=> throw error when using v1 apis for multichain

.github/workflows/code-quality.yml, package.json, src/abi/ERC1155.json, src/abi/ERC721.json, src/sdk.ts, test/sdk/getBalance.spec.ts
Fixes getBalance and adds tests. Fixes https://github.com/ProjectOpenSea/opensea-js/issues/1093
=> Fix getBalance

src/sdk.ts, test/sdk/misc.spec.ts
Fix common user issue when using an accountAddress that isn't available through the provider or wallet 
Fixes #1097 and many other issues
=> Fix common user issue when using an accountAddress that isn't available through the provider or wallet 

src/constants.ts, src/utils/utils.ts, test/sdk/misc.spec.ts
fixes https://github.com/ProjectOpenSea/opensea-js/issues/1109#issuecomment-1642311112
=> add addresses for polygon (matic/mumbai) and klaytn shared storefront

src/sdk.ts
Tries to improve/fix error seen in https://github.com/ProjectOpenSea/opensea-js/discussions/1113
=> improve _checkAccountIsAvailable function

src/api/types.ts
=> Fix ProtocolData import path in src/api/types.ts

package.json, src/types.ts, src/utils/utils.ts
base went live yesterday, adding here & will update the docs
=> feat: add base l2 chain identifiers

.mocharc-integration.json, .mocharc-unit.json, package.json
=> Fix running tests in Windows dev env

package.json
=> Bump version to v6.1.7

renovate.json
Gets a little spammy at current schedule. Already did this on our internal dependabot stuff
dunno why they went with natural language configuration options like this lol but just implemented based on this:
https://docs.renovatebot.com/key-concepts/scheduling/
=> chore: reduce renovate bot frequency to weekly

src/api/api.ts, src/orders/utils.ts, test/integration/getNFTs.spec.ts
Adds new v2 API endpoint: https://docs.opensea.io/reference/retrieve-nfts-by-account
=> add getNFTsByAccount

README.md, developerDocs/getting-started.md, src/constants.ts, src/sdk.ts, src/types.ts, test/integration/postOrder.spec.ts, test/sdk/misc.spec.ts, test/utils/utils.ts
Fixes https://github.com/ProjectOpenSea/opensea-js/discussions/1159
=> Add english auctions

package.json
=> Bump version to 6.1.8

src/utils/utils.ts
Added Mumbai WETH address, So that English auctions can be created over `mumbai` chain.
Adding Mumbai WETH token address to `getWETHAddress` function
=> Add mumbai WETH address

developerDocs/faq.md, developerDocs/getting-started.md, developerDocs/quick-start.md, src/api/api.ts, src/sdk.ts, test/integration/postOrder.spec.ts
improves docs
- default api v1 chain is now sepolia instead of goerli
- dutch auctions no longer supported on opensea
- some contributions by @Palisanka from #1187
=> Improve docs

package.json, src/sdk.ts
=> address validation fix, prep 6.1.10 release 

.github/workflows/stale.yml
Add "informational" label exemption to stale workflow
=> Add "informational" label exemption to stale workflow

src/constants.ts, src/sdk.ts, test/integration/postOrder.spec.ts
Adds english auction zone address for testnets. Fixes #1220
=> Fix english auction zone on testnets

src/api/api.ts
fixes https://github.com/ProjectOpenSea/opensea-js/discussions/1200
=> fix maker and taker param docs

package.json
=> Bump version to v6.1.11

package-lock.json, package.json, src/sdk.ts
adds tx overrides from latest seaport-js release
=> Add tx overrides

.github/workflows/docs.yml
Use GH Application as an installable app to gain write access and push to the developer-docs repo
=> Use GitHub app for token generation

package-lock.json, package.json, src/types.ts, src/utils/utils.ts
Arbitrum goerli is being deprecated. Arbitrum sepolia is the recommended path forward for arbitrum developers using testnets
Replace arbitrum goerli support with arbitrum sepolia support
=> Replace arbitrum goerli support with arbitrum sepolia support

developerDocs/getting-started.md, package.json, src/api/api.ts, src/api/types.ts, src/orders/types.ts, src/orders/utils.ts, src/sdk.ts, test/integration/getListingsAndOffers.spec.ts
add API endpoints:
- get all listings and offers
- get best listing and offer
also fixes a couple typos
=> Add get all listings/offers, get best listing/offer

package.json, src/api/api.ts
was checking `response.ok` instead of `response.ok()`
=> fix api errors response

src/constants.ts, src/sdk.ts, src/utils/utils.ts
float multiplication was leading to rounding errors in basis points calculation
=> fix basis points rounding

package.json, src/api/api.ts
=> Add pagination to getBestListings

package.json, src/api/api.ts, test/integration/postOrder.spec.ts
=> Fix import for browser compatibility

package.json, src/sdk.ts
=> Fix Seaport v1.5 fulfillments

developerDocs/getting-started.md
=> docs: add collection offer example

package.json, src/types.ts, src/utils/utils.ts
https://docs.opensea.io/changelog/polygon-amoy-testnet
=> replace mumbai with polygon amoy testnet

package.json
=> Update package.json - bump version for release

src/api/api.ts
now that the bug is patched (https://github.com/ethers-io/ethers.js/issues/4663)
=> Use ethers setThrottleParams

package.json
=> Bump version to 7.1.11 for release

package.json
=> Downgrade back to 7.1.10 for release

package.json, src/types.ts, src/utils/utils.ts
=> Add sei mainnet and testnet chain

package.json, src/constants.ts, src/sdk.ts
=> add zone parameter to createListing, make default zone ZeroAddress

package.json, src/types.ts, src/utils/utils.ts
=> Release B3

developerDocs/getting-started.md
Found a typo in the document.
“Getting Start” -> "Getting Started"
This correction makes the sentence more communicative.
=> docs: clenup getting-started.md

package.json, src/types.ts, src/utils/utils.ts
=> Release Bera chain

src/utils/utils.ts
this should be WBERA for opensea offers
=> fix berachain weth address from weth to wbera

package.json, src/types.ts, src/utils/utils.ts
=> Release ApeChain and Flow testnet

src/sdk.ts
=> Update createOffer excludeOptionalCreatorFees to default true

package.json, src/types.ts, src/utils/utils.ts
=> Release Flow

src/sdk.ts
=> fix minor docs typo sdk.ts

package.json, src/types.ts, src/utils/utils.ts
=> Release Ronin

package.json, src/types.ts, src/utils/utils.ts
=> feat: release abstract

package.json
=> Update package.json to v7.1.19 for release

src/types.ts, src/utils/utils.ts
OpenSea supports unichain but opensea-js does not. This makes me sad.
To remedy my sadness, I am adding Unichain to opensea-js.
Addresses #1731
=> Add Unichain
