ProjectOpenSea/opensea-js

package.json
src/seaport.ts
src/utils/utils.ts

Sign typed data v2,3,4 are not supported by a number of providers. Changing to just use regular signTypedData. Also removing JSON.stringify as some wallet providers sanitize the message

Fix sign typed data to be compatible for more providers

---

src/__tests__/api/api.ts
src/__tests__/seaport/orders.ts
src/api.ts
src/types.ts

We don't support search as a query param in the Asset & Bundle endpoints anymore

Remove search field from Asset & Bundle API lookups

---

package-lock.json
package.json

fixes #451 for clients using `npm` by tweaking the dependencies of `wyvern-js` to ensure only a single version of `@0x/utils` is installed and it is the patched git url v6.5.0. Other `@0x/...` deps must be compatible with `@0x/utils` v6.5.0.
Unfortunately, `yarn` seems to ignore the package-lock.json and installs `@0x/web3-wrapper@7.3.5` (satisfying import of `^7.3.0` by some other `@0x/...` deps) which requires `@0x/utils@^6.5.3`. Clients using `yarn` can temporarily override the `@0x/utils` deps with a `resolution` in `package.json` to the patched version like this:
```
"resolutions": {
"@0x/utils": "https://github.com/ProjectOpensea/0x-tools/raw/provider-patch/utils/0x-utils-6.5.0.tgz"
}
```

fix: @0x/utils dep throwing in production builds

---

src/constants.ts

While `0x9b814233894cd227f561b78cc65891aa55c62ad2` zone does not throw an error when trying to create an order, it does throw execution reverted when trying to fulfill that order. #624

Update DEFAULT_ZONE_BY_NETWORK (rinkeby)

---

src/__tests__/sdk/misc.ts
src/constants.ts
src/sdk.ts
src/utils/utils.ts

Update asset token addresses when creating a buy order or creating a sell order to remap the shared storefront address to the lazy mint adapter address

Update order assets to use lazy mint adapter address in place of shared storefront address

---

package.json
src/__tests__/constants.ts
src/__tests__/sdk/fees.ts
src/sdk.ts
src/types.ts
src/utils/utils.ts

Support multi creator fees in SDK by: 
1. adding `Fees` type that holds both Opensea and seller fee maps 
2. adding fees to collection type 
3. converting single consideration item to list of consideration items derived from the fee map in `getFees`

support multi creator fees in the sdk 

---

src/sdk.ts

Fixes error thrown when iterating over `fees?.sellerFees` key/value pairs. Instantiating a new `Map` object required for typescript (originally had it pull basis points using `sellerFees[recipient]`, but the `Fees` ts definition defines the values of `Fees` keys as `Map`s) 
Alternatively, we could avoid creating a map here by either: 
1. update `Fees` ts definition to just accept objects since the keys are strings anyway 
2. update `utils.collectionFromJSON` to instantiate `openseaFees` and `sellerFees` as `Map` entities like: 
```javascript
fees: {
openseaFees: new Map(Object.entries(collection.fees.opensea_fees)) || new Map(),
sellerFees: new Map(Object.entries(collection.fees.seller_fees)) || new Map(),
},
```

fix error in fee iteration

---

src/sdk.ts
src/utils/utils.ts

No functionality change - just cleaner syntax :)

a cleaner way to make sure `Fees` submap is the correct type

---

src/sdk.ts

`Object.keys` over a `Map` doesn't work; it will return an empty array.

Iterate over sellerFees Map correctly

---

package.json
src/sdk.ts

Allow users to pass in optional salt and/or domain during order creation
- If a salt && domain are passed in, salt will be used for order (domain will be ignored)
- If only salt is passed in, salt will be used for order
- If only domain is passed in, domain will be hashed and added to first four bytes of salt, middle 20 bytes will be empty, last 8 bytes will be random
- If neither salt nor domain are passed in, first 24 bytes will be empty, last 8 bytes will be random
- Logic for salt creation is stored in `createOrder` in `seaport-js`

Add salt and domain params to createBuyOrder and createSellOrder

---

package.json
src/sdk.ts

- Add optional `domain` param to fulfillment methods to match functionality in `seaport-js` [PR](https://github.com/ProjectOpenSea/seaport-js/pull/117)
- Appends tags to fulfillment calldata

update fulfillment methods to accept domain

---

src/api.ts

Sending the SDK version in our requests will make it quicker to diagnose issues which are only seen in the SDK and not the API.

Add sdk version as header in API requests

---

src/utils/utils.ts

Looks like `isValidProtocol()` that was added recently will fail because the constants used in validProtocolAddresses are not also passed through `Web3.utils.toChecksumAddress()`
Example of failing code:
```js
const isValidProtocol = (protocolAddress) => {
const checkSumAddress = Web3.utils.toChecksumAddress(protocolAddress);
const validProtocolAddresses = [
CROSS_CHAIN_SEAPORT_ADDRESS,
CROSS_CHAIN_SEAPORT_V1_4_ADDRESS,
];
return validProtocolAddresses.includes(checkSumAddress);
};
// This should be valid and return true
console.log(isValidProtocol(CROSS_CHAIN_SEAPORT_ADDRESS)); // returns false
```
Added a map for `validProtocolAddresses` to make sure all valid protocol addresses are also the checksum version.
```js
// [...]
const validProtocolAddresses = [
CROSS_CHAIN_SEAPORT_ADDRESS, …
```

Add toChecksumAddress to constants in isValidProtocol

---

src/sdk.ts

Issue is brought up here: https://github.com/ProjectOpenSea/opensea-js/issues/870
We use ```seaport.fulfillOrder``` to fulfill orders, and we pass the ```order.protocolData``` to that method. The protocolData needs to have a set signature, and I previously only update the orderV2 object

fix fulfillment

---

package.json
src/api.ts

Adding the `package.json` import caused the build folder to change from:
lib
- index.js
-skd.js
to:
lib
- src
- - index.js
- -sdk.js
- package.json

Remove package.json dependency

---

package-lock.json
package.json

I added the SDK to a local web app and sent a `unwrapWeth` call to make sure the listeners still worked. Upgrading this dependency to remove a child dependency on an old version of `node-fetch`

Upgrade dependency

---

.github/workflows/code-quality.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/npm-publish.yml
package.json

Ensures we're building and testing consistent versions of node. We'll build and test on our standardized version and additionally test the minimum supported Node version.

Build and Test Supported Node Versions

---

src/api.ts
src/constants.ts
src/index.ts
src/sdk.ts
src/types.ts
src/utils/schemas/schema.ts

Functions Removed:
- encodeCall
- encodeSell
- encodeAtomicizedBuy
- encodeAtomicizedSell
- _makeMatchingOrder
- _sellOrderValidationAndApprovals
- _validateOrder
- _getMetadata
- authorizeOrder
- getNonce
- getOrderCreateWyvernExchangeAddress 
- encodeReplacementPattern

Remove Wyvern Specific Functions

---

README.md
src/sdk.ts

The naming conventions were confusing between `getTokenBalance` and `getAssetBalance` since they are all tokens and assets. Instead we decided to use a single function for all schemas.

Consolidate to one getBalance function

---

.github/workflows/stale.yml

Set `ascending: true` to close oldest issues first (reaching max operations-per-run when going descending and not closing any issues)

Fix stale.yml

---

renovate.json

By default, Renovate raises PRs but leaves them to someone or something else to merge them. By configuring this setting, you allow Renovate to automerge PRs or even branches. Using automerge reduces the amount of human intervention required.
Instead of automerging all PRs,  leave major dependency updates to a human to review first.
Ref: https://docs.renovatebot.com/configuration-options/#automerge

Add automerge to renovate config

---

.eslintrc.js
.prettierignore
package.json
src/api.ts
test/api/api.spec.ts

Removes `isomorphic-unfetch` dependency in favor of ethers fetchJson that uses fetch or node http/s under the hood. Should help alleviate browser build pipeline challenges.
Down to 2 dependencies in this package!

Use ethers fetchJson

---

package-lock.json
package.json
src/sdk.ts
test/integration/postOrder.spec.ts

Fixes #1022 
BigNumberish was being parsed as FixedNumber and cast to string. Instead casted BigNumberish to string directly.
Changed integration tests to use numbers instead of strings.

Fixes underflow when try to use fractional ETH as number in orders

---

package.json
src/orders/types.ts
src/orders/utils.ts
src/sdk.ts
test/utils/utils.ts

We wanted to get unit price of the lowest listing (aka a "quote" of a given NFT asset from Opensea) and needed an easier way to access the quantity field for a given order, as the current price is given as a total rather than a unit price. 
For more details see: https://github.com/ProjectOpenSea/opensea-js/issues/1064
expose the "remaining_quantity" field from API.

expose new field for remaining quantity

---

package.json
src/orders/types.ts
src/orders/utils.ts
test/utils/utils.ts

Adding a new field to types which already is being returned by the API.
Fixes #1086

expose new field for remaining quantity in OrderV2 type (#1086)

---

src/sdk.ts

extraData is only provided in an array of Advanced Orders, improves the guard
Fixes #1153
TODO need to add a local hardhat forked setup for an integration test to get varying valid orders (basic, advanced with protection, etc.) and fulfill them on the fork and ensure the tx is successful. might try to add this today.

Fix getting extraData in order fulfillment

---

.eslintrc.js
test/api/getOrders.spec.ts
test/utils/utils.ts

Fixes issues like https://github.com/ProjectOpenSea/opensea-js/issues/1164 https://github.com/ProjectOpenSea/opensea-js/issues/1121
Example error with this rule added:

Add eslint rule to restrict importing from "src"

---

src/sdk.ts
test/sdk/misc.spec.ts

During #1198 #1204 while trying to fix esm imports replacing `instanceof` to constructor name comparison changed how the prototype inheritance chain is compared, and not all providers that inherit the base `JsonRpcProvider` are now equally compared. 
This PR updates the comparison to see if the provider simply includes `listAccounts()`, which all base `JsonRpcProviders`  do. This should fix using `window.ethereum` as well, and improves the error message for more helpful debugging.
Fixes #1221

Fix provider to use any provider that includes "listAccounts" (e.g. Web3Provider)

---

README.md
developerDocs/advanced-use-cases.md
developerDocs/getting-started.md
developerDocs/overview.md
package.json
src/sdk.ts
src/types.ts
src/utils/utils.ts
test/integration/postOrder.spec.ts
test/sdk/misc.spec.ts

renames:
- `createSellOrder` to `createListing`
- `createBuyOrder` to `createOffer`
creates deprecated aliases for backward compact
misc cleanup and fixes:
- add more typedocs
- improve type for `Asset` when tokenId or tokenStandard is required

Rename `createSellOrder` to `createListing` and `createBuyOrder` to `createOffer`, keep aliases for backward compat

---

package.json
src/api/api.ts
src/api/types.ts
test/integration/getListingsAndOffers.spec.ts

fix passing next cursor for getAllListings/getAllOffers

---

package.json
src/api/api.ts

Throw with error messages or SERVER_ERROR if network response is not ok

---

package.json
src/sdk.ts
src/types.ts

Adds transfer() helper for assets

Add asset transfer function

---

src/api/types.ts
src/types.ts
src/utils/utils.ts

adds new api fields:
- collection.totalSupply
- collection.createdDate
- nft.traits

add new api fields

---

src/api/api.ts

Fix rate limit errors: add 1s timeout to retry throttle

---

developerDocs/getting-started.md
src/api/api.ts
src/orders/utils.ts
src/sdk.ts
test/integration/postOrder.spec.ts

add trait offers

---

src/api/api.ts

OpenSeaSDK does not use the `apiBaseUrl` parameter in the `apiConfig`, instead overwrites it with the default parameters.
The PR allows to again overwrite the base url as the user pleases.

fix(sdk): allow apiBaseUrl overwrite

---

package.json
src/api/types.ts
test/integration/getNFTs.spec.ts

Adds missing fields: `creator`, `owners`, `opensea_url`, and `rarity`

add missing fields to Get NFT

---

package-lock.json
src/constants.ts
src/sdk.ts

adding SIGNED_ZONE to be able to cancel id offers created using the sdk.
added  export const SIGNED_ZONE = "0x000056f7000000ece9003ca63978907a00ffd100" and pushed to createOffer()

Add zone parameter to createOffer function for SignedZone support

---

src/sdk.ts

Fix the issue where collections with zero fees are not handled correctly, causing unnecessary errors.
Filter out zero-value fees and add a conditional check to process fees only when they are greater than zero.
Related issue: [#1531](https://github.com/ProjectOpenSea/opensea-js/issues/1531)

support for collection with 0% Opensea fee

---

src/api/types.ts
test/integration/getListingsAndOffers.spec.ts

Updated Price type (mismatch with API response) and added a few asserts examples for price in "BestOffer"
When implementing "opensea-js" package, I can't use the Price type. The API response doesn't contain a "current" field.
Updated the type, removed the "current" level. Also added a few asserts in the unit test to validate the format of the API call.
Also, maybe it's a nice recommendation to include "zod" so you can validate API responses against a schema during tests

Updated Price type

---

developerDocs/advanced-use-cases.md
developerDocs/faq.md

developerDocs/advanced-use-cases.md
amount be sent - amount will be sent  `correction`
developerDocs/faq.md
Why is there is no SDK - Why is there no SDK  `deleted duplicate is `

fix spelling issues

---

src/sdk.ts
src/utils/utils.ts
test/utils.spec.ts

we only support seaport 1.6 now

Remove seaport 1.5 code

---

developerDocs/getting-started.md
src/sdk.ts

**developerDocs/getting-started.md**
`we recommend even doing 0!` - `we recommend even using 0!` -- _`Using` more accurately describes setting a value for a parameter, while `doing` refers more to performing an action. When it comes to numerical values, `using` is more idiomatic and technically correct._
**src/sdk.ts**
`order.  For order `- `order. For order` -- _deleted double space_

minor docstring fixups

---

src/types.ts
src/utils/utils.ts

Add support for Shape Network
Official Website: https://shape.network/ 
Token: ETH
Shape is a creator-focused EVM-equivalent blockchain. Shape creators receive back a portion of the gas spent by users using a concept called “[gasback](https://docs.shape.network/documentation/building-on-shape/gasback).”
The Shape network is compatible with EVM wallets, and uses ETH bridged to Shape.
Add Shape and testnet to Chain as well as util functions getChainId and getWETHAddress

Add Shape to Chain enum

---

package-lock.json
package.json
src/api/api.ts
src/types.ts
test/api/api.spec.ts

Fixes https://github.com/ProjectOpenSea/opensea-js/issues/1668
This PR adds support for exposing the `retry-after` header from OpenSea API rate limit responses, enabling SDK users to implement proper backoff mechanisms when encountering rate limits.
- **Refactored rate limit error handling** into a clean helper function `_createRateLimitError()`
- **Added retry-after support** for both 429 and 599 status codes by extending Error objects with `retryAfter` and `responseBody` properties
- **Maintained full backward compatibility** - existing error handling continues to work unchanged
- **Added comprehensive tests** with sinon mocking to verify rate limit error behavior
- **Added TypeScript support** via `OpenSeaRateLimitError` interface
```typescript
try {
await sdk.createOffer(/* ... */);
} …
```

feat: add retry-after header support for rate limit errors (non-breaking)
